version: "3"
services:
  selenium-hub:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/status"]
      interval: 30s
      timeout: 10s
      retries: 5
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      selenium-hub:
        condition: service_healthy